### ISSUE TITLE
This works great in the normal UI, but not in service portal.

### ISSUE THREAD

**Issue by jacebenson** [MBahrSNC/snGoogleTranslate#1]
Just like title says.

Works great in normal UI, but not in the SP.  Any plans to update this to work on a menu in portal?

**Comment by MBahrSNC** [comment]
Hi Jace, yes I plan on creating a SP header with this feature. 

I have a prototype in my dev environment, just need to finalize it.

**Comment by MBahrSNC** [comment]
Added Service Portal Header.
